# Generated by Django 4.0.4 on 2022-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=0)),
                ('etcs', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('school_year', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('topics', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lusofona_url', models.CharField(max_length=100)),
                ('linkdin', models.CharField(max_length=100)),
            ],
        ),
    ]
