# Generated by Django 4.0.4 on 2022-05-17 16:20

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('portfolio', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkdin', models.CharField(max_length=100)),
            ],
            bases=(portfolio.models.Person, models.Model),
        ),
    ]
